FROM php:8.2.0alpha2-fpm
RUN apt-get update && apt-get upgrade -y && apt-get install -y git
RUN apt-get install -y libzip-dev zip && docker-php-ext-install zip
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN docker-php-ext-install pdo pdo_mysql && docker-php-ext-enable pdo pdo_mysql
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer